services:
  popular_movies:
    image: popular-movies-prod
    build:
      context: .
      dockerfile: Dockerfile
    container_name: popular_movies_prod
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.production
