services:
  popular_movies:
    image: popular-movies-dev
    build:
      context: .
      dockerfile: Dockerfile
    container_name: popular_movies
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    command: ["npm", "run", "dev"]
